#######################################################
##                                                   ##
##          Config.yml for GC Stats Tracker          ##
##                                                   ##
#######################################################

## Randomly broadcasts reminders to earn achievements with /gca for rewards
broadcastInfo:
  enabled: false
  intervalMinutesMin: 10
  intervalMinutesMax: 20
  message:
    - '&7==================[ &2Achievements &7]================='
    - '&fEach achievements with /gca to earn points!'
    - '&fSpend points at /gca shop'
    - '&7================================================='

  
## Happens when a player earns an achievement
achievements:
  doFirework: true
  doMessage: true
  giveRewards: true
  globalPoints: false # if true, points carry across, and can be redeemed on, multiple servers
  serverIcon: GRASS

## Name of the server in the database
server:
  name: "defaultName"
  icon: "INK_SACK"
  iconDamage: 2
  
data:
  SQLEnabled: true