main: jdz.statsTracker.GCStats
name: gcStats
version: 1.1
author: Jonodonozym
description: Tracks player stats and achievements, storing them on an SQL database
depend: [JBU]
softdepend: [BountyHunters,KOTH,EventOrganizer,PlaceholderAPI,LeaderHeads]

commands:
  gca:
    description: Displays your achievements
    aliases: [gcach,gcachievement,gcachievements,ach]
    usage: |
      /gca - shows your achievements for all servers
      /gca about - info about the plugin
  gcs:
    description: Displays your stats
    aliases: [gcstats,gcstat,stats,s]
    usage: |
      /gcs - shows your stats for your current server
      /gcs servers - lists avaliable servers
      /gcs (server) - shows stats for another server
      /gcs (player) - shows stats for another player
      /gcs (player) (server) - shows stats for another player on another server
      /gcs about - info about the plugin
  gco:
    description: Displays your current objectives
    aliases: [objectives, objective, obj]
      
permissions:
  gcs.top:
    description: allows use of /gcs top and /gcs rank commands
    default: false