main: jdz.statsTracker.GCStats
name: gcStats
version: 1.1
author: Jonodonozym
description: Tracks player stats and achievements, storing them on an SQL database
depend: [JBU]
softdepend: [BountyHunters,KOTH,EventOrganizer,PlaceholderAPI,LeaderHeads]

commands:
  ach:
    description: Displays your achievements
    aliases: [gcach,gcachievement,gcachievements,gca]
    usage: |
      /gca - shows your achievements for all servers
      /gca about - info about the plugin
  s:
    description: Displays your stats
    aliases: [gcstats,gcstat,stats,gcs]
    usage: |
      /gcs - shows your stats for your current server
      /gcs servers - lists avaliable servers
      /gcs (server) - shows stats for another server
      /gcs (player) - shows stats for another player
      /gcs (player) (server) - shows stats for another player on another server
      /gcs about - info about the plugin
  obj:
    description: Displays your current objectives
    aliases: [objectives, objective, gco]
      
permissions:
  gcs.top:
    description: allows use of /gcs top and /gcs rank commands
    default: false