main: jdz.statsTracker.main.Main
name: gcStats
version: 1.0
author: Jonodonozym
description: Tracks player stats and achievements, storing them on an SQL database
softdepend: [BountyHunters,KOTH,EventOrganizer]

commands:
  gca:
    description: Displays your achievements
    aliases: [gcach,gcachievement,gcachievements]
    usage: |
      /gca - shows your achievements for all servers
      /gca about - info about the plugin
  gcs:
    description: Displays your stats
    aliases: [gcstats,gcstat]
    usage: |
      /gcs - shows your stats for your current server
      /gcs servers - lists avaliable servers
      /gcs (server) - shows stats for another server
      /gcs (player) - shows stats for another player
      /gcs (player) (server) - shows stats for another player on another server
      /gcs about - info about the plugin
      